linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - revive
    - gosec
issues:
  exclude-use-default: false
