package domain

import "context"

// Vector represents a mathematical vector generated by an embedding model.
// pgvector in PostgreSQL natively maps to []float32.
type Vector []float32

// EmbeddingProvider defines the contract for any service that converts text into vector embeddings.
type EmbeddingProvider interface {
	// GenerateEmbeddings takes a batch of strings and returns their corresponding vector representations.
	GenerateEmbeddings(ctx context.Context, texts []string) ([]Vector, error)

	// Dimensions returns the exact size of the generated vectors.
	Dimensions() int
}
